---
params:
  chapter: 13
  species: "Rougheye and Blackspotted Rockfish"
  complex: "yes"
  area: "Gulf of Alaska"
  tier: 3
  dft_title: "`r params$chapter`. Assessment of the `r params$species` stock in the `r params$area`"

author: "Jane Y. Sullivan, S. Kalei Shotwell, Dana H. Hanselman, Peter-John F. Hulson, Benjamin C. Williams, Ellen M. Yasumiishi, and Bridget E. Ferriss"
date: "November 2022"
  
# do not adjust the YAML below this line  
# ------------------------------------------------
# output: rmarkdown::html_vignette

output:
  bookdown::pdf_document2:
     toc: false
     number_sections: false
     latex_engine: xelatex

fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in
      
fig_caption: true
  
header-includes:
  
   \usepackage{sectsty}
   \allsectionsfont{\centering}
   \usepackage{xcolor}
   
   \usepackage[labelsep=period]{caption}
   \usepackage{float}
   \let\origfigure\figure
   \let\endorigfigure\endfigure
   \renewenvironment{figure}[1][2] {
      \expandafter\origfigure\expandafter[H]
    } {
      \endorigfigure
   }
   
   \renewcommand{\thefigure}{`r params$chapter`-\arabic{figure}}
   \renewcommand{\thetable}{`r params$chapter`-\arabic{table}}
   \pagenumbering{gobble}
---

```{r, echo = F}
if(params$complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", params$species, " stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", params$species, " stock complex in the ", params$area)  
  }


```

---
title: `r title`
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(vroom)
library(here)
library(dplyr)
library(tidyr)
library(flextable)

# global 
endyr = 2022

curr_type <- if(endyr %% 2 == 0) {'partial'} else {'full'}
past_type <- if(endyr %% 2 == 0) {'full'} else {'partial'}

source(here::here("functions4proj.R"))

# Estimates
# 2022 2023 | 2023 2024
# Status
# 2020 2021 | 2021 2022

# current and past two years assessment summary tables. tier designations saved
# separately due to character format
curr <- vroom(here::here(paste0(endyr, "_", curr_type), "exec_summary_tbl.csv"))
curr_tier <- vroom(here::here(paste0(endyr, "_", curr_type), "tier_design.csv"))
past <- vroom(here::here(paste0(endyr-1, "_", past_type), "exec_summary_tbl.csv"))
past_tier <- vroom(here::here(paste0(endyr-1, "_", past_type), "tier_design.csv"))
past2 <- vroom(here::here(paste0(endyr-2, "_", curr_type), "exec_summary_tbl.csv"))
# catch data summaries
catch <- vroom(here::here(paste0(endyr, "_", curr_type), "proj_catch_assumptions.csv"))

# 1) test for determining whether overfishing is occurring is based on the
# YEAR-1 catch compared to the YEAR-1 OFL
tof1_catch <- round(catch[catch$year == endyr-1,]$catch, 0)
tof1_ofl <- round(past2[past2$item == 'OFL (t)', 2], 0)
if(tof1_catch < tof1_ofl) {tof1 <- "No"} else {tof1 <- "Yes"}

# 2) test for  overfished
tof2_ssb <- round(as.numeric(curr[curr$item == 'Projected female spawning biomass (t)', 2]), 0)
tof2_B35 <- round(as.numeric(curr[curr$item == 'B35%', 2]), 0)
if(tof2_B35 < tof2_ssb) {tof2 <- "No"} else {tof2 <- "Yes"}

# 3) test for  approaching a condition of being overfished
tof3_ssb <- round(as.numeric(curr[curr$item == 'Projected female spawning biomass (t)', 3]), 0)
tof3_B35 <- round(as.numeric(curr[curr$item == 'B35%', 3]), 0)
if(tof3_B35 < tof3_ssb) {tof3 <- "No"} else {tof3 <- "Yes"}

exec_tbl_dat <- prep_exec_tbl(curr, curr_tier, past, past_tier)

```


```{r}
exec_tbl(data = exec_tbl_dat, endyr = endyr, tier = 3, catch = catch)
```

